{{- if and .Values.config.enabled .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-gateway.fullname" . }}-config
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}
{{- end }}