apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-gateway.fullname" . }}
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "edge-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edge-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edge-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MQTT_BROKER_URL
              value: {{ .Values.mqtt.broker.url | quote }}
            {{- if .Values.mqtt.broker.username }}
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "edge-gateway.fullname" . }}-mqtt-credentials
                  key: username
            {{- end }}
            {{- if .Values.mqtt.broker.password }}
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "edge-gateway.fullname" . }}-mqtt-credentials
                  key: password
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if and .Values.config.enabled .Values.config.data }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          {{- end }}
      {{- if and .Values.config.enabled .Values.config.data }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "edge-gateway.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}