{{- if or .Values.mqtt.broker.username .Values.mqtt.broker.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-gateway.fullname" . }}-mqtt-credentials
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mqtt.broker.username }}
  username: {{ .Values.mqtt.broker.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.mqtt.broker.password }}
  password: {{ .Values.mqtt.broker.password | b64enc | quote }}
  {{- end }}
{{- end }}