name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  basic-build:
    name: Basic Build Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Check Go files
      run: |
        if [ -d "code/edge-gateway" ] && [ -f "code/edge-gateway/main.go" ]; then
          cd code/edge-gateway
          go version
          if [ -f "go.mod" ]; then
            go mod tidy
            go build -v ./...
          else
            echo "No go.mod file found, creating one"
            go mod init github.com/dcentral-platform/monorepo/edge-gateway
            go build -v ./...
          fi
        else
          echo "No Go code to build at this time"
        fi
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Check Node.js files
      run: |
        if [ -d "code" ] && [ -f "code/package.json" ]; then
          cd code
          node --version
          npm --version
          echo "Node.js setup complete"
        else
          echo "No Node.js code to build at this time"
        fi
    
    - name: Create build summary
      run: |
        echo "# Build Summary" > build_summary.md
        echo "- Go version: $(go version)" >> build_summary.md
        echo "- Node.js version: $(node --version)" >> build_summary.md
        echo "- NPM version: $(npm --version)" >> build_summary.md
        echo "- Date: $(date)" >> build_summary.md
        echo "Build check completed successfully!" >> build_summary.md
    
    - name: Upload build summary
      uses: actions/upload-artifact@v4
      with:
        name: build-summary
        path: build_summary.md