name: Basic Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at midnight
  workflow_dispatch:

jobs:
  dependency-check:
    name: Dependency Scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Check Go dependencies
        run: |
          if [ -f "./code/edge-gateway/go.mod" ]; then
            cd ./code/edge-gateway
            go list -json -m all > go-deps.json
          else
            echo "No go.mod found in edge-gateway directory"
            touch go-deps-not-found.txt
          fi
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install npm-audit-resolver
        run: npm install -g npm-audit-resolver
      
      - name: Check npm dependencies
        run: |
          if [ -f "./code/package.json" ]; then
            cd ./code
            npm audit --json > npm-audit.json || true
          else
            echo "No package.json found in code directory"
            touch npm-audit-not-found.txt
          fi
          
          if [ -f "./code/contracts/package.json" ]; then
            cd ./code/contracts
            npm audit --json > npm-audit-contracts.json || true
          else
            echo "No package.json found in contracts directory"
            touch npm-audit-contracts-not-found.txt
          fi
      
      - name: Create security report
        run: |
          mkdir -p reports
          echo "# Security Scan Report" > reports/security_report.md
          echo "## Dependency Check" >> reports/security_report.md
          echo "Scan completed: $(date)" >> reports/security_report.md
          echo "Basic scanning enabled. For advanced scanning, enable GitHub Advanced Security." >> reports/security_report.md
          
      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: reports
  
  secret-scanning:
    name: Basic Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for hardcoded secrets
        run: |
          mkdir -p reports
          echo "# Secret Scanning Report" > reports/secret_scan.md
          echo "Scan completed: $(date)" >> reports/secret_scan.md
          echo "Checking for common patterns..." >> reports/secret_scan.md
          
          # Simple pattern matching for common secret patterns
          grep -r -E "(password|api.?key|secret|token)['\"]?\s*[:=]\s*['\"]" \
            --include="*.js" --include="*.go" --include="*.json" --include="*.yaml" \
            --include="*.yml" . || echo "No obvious secrets found" >> reports/secret_scan.md
          
          echo "Basic scanning enabled. For advanced scanning, enable GitHub Advanced Security." >> reports/secret_scan.md
      
      - name: Upload secret scanning report
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-report
          path: reports